# Generated by Django 4.2.1 on 2023-05-31 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_company_contacts_company_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
