# Generated by Django 4.2.1 on 2023-06-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_slider_image_alter_company_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя')),
                ('surname', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=45, verbose_name='Электронная почта')),
                ('theme', models.CharField(choices=[('Дом', 'Заказать строительство жилого дома'), ('Инженерное сооружение', 'Заказать строительство инженерного сооружения'), ('Отделка', 'Заказать отделку помещения'), ('Вопрос', 'Другой вопрос')], default='Дом', max_length=100, verbose_name='Тема')),
                ('note', models.CharField(max_length=500, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.DeleteModel(
            name='Feedback_form',
        ),
        migrations.AlterModelOptions(
            name='company_contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты компании'},
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='email',
            field=models.CharField(max_length=45, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='number_phone',
            field=models.CharField(help_text='В формате +79998887766', max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='floor_height',
            field=models.CharField(max_length=10, null=True, verbose_name='Высота одного этажа'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_project',
            field=models.CharField(max_length=45, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество санузлов'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_floors',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_area',
            field=models.CharField(max_length=20, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_project',
            field=models.CharField(max_length=45, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='slider_image',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Переход на ресурс'),
        ),
        migrations.AlterField(
            model_name='slider_image',
            name='link',
            field=models.ImageField(null=True, upload_to='images/slider', verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='slider_image',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
